# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui',
# licensing of 'untitled.ui' applies.
#
# Created: Thu Oct 14 09:11:44 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setMinimumSize(QtCore.QSize(21, 21))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.char_name = QtWidgets.QLineEdit(self.centralwidget)
        self.char_name.setGeometry(QtCore.QRect(20, 20, 241, 20))
        self.char_name.setObjectName("char_name")
        self.stats = QtWidgets.QGroupBox(self.centralwidget)
        self.stats.setGeometry(QtCore.QRect(8, 75, 133, 144))
        self.stats.setAlignment(QtCore.Qt.AlignCenter)
        self.stats.setFlat(True)
        self.stats.setObjectName("stats")
        self.st_str_origin = QtWidgets.QLineEdit(self.stats)
        self.st_str_origin.setGeometry(QtCore.QRect(35, 14, 22, 20))
        self.st_str_origin.setMaxLength(2)
        self.st_str_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_str_origin.setObjectName("st_str_origin")
        self.st_str_mod = QtWidgets.QLabel(self.stats)
        self.st_str_mod.setGeometry(QtCore.QRect(107, 14, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_str_mod.setFont(font)
        self.st_str_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_str_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_str_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_str_mod.setObjectName("st_str_mod")
        self.st_str_misc = QtWidgets.QLineEdit(self.stats)
        self.st_str_misc.setGeometry(QtCore.QRect(59, 14, 22, 20))
        self.st_str_misc.setMaxLength(2)
        self.st_str_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_str_misc.setObjectName("st_str_misc")
        self.st_str_all = QtWidgets.QLabel(self.stats)
        self.st_str_all.setGeometry(QtCore.QRect(83, 14, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_str_all.setFont(font)
        self.st_str_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_str_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_str_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_str_all.setObjectName("st_str_all")
        self.pushButton_13 = QtWidgets.QPushButton(self.stats)
        self.pushButton_13.setGeometry(QtCore.QRect(2, 13, 32, 22))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.stats)
        self.pushButton_14.setGeometry(QtCore.QRect(2, 34, 32, 22))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.stats)
        self.pushButton_15.setGeometry(QtCore.QRect(2, 76, 32, 22))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.stats)
        self.pushButton_16.setGeometry(QtCore.QRect(2, 97, 32, 22))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.stats)
        self.pushButton_17.setGeometry(QtCore.QRect(2, 118, 32, 22))
        self.pushButton_17.setObjectName("pushButton_17")
        self.st_con_misc = QtWidgets.QLineEdit(self.stats)
        self.st_con_misc.setGeometry(QtCore.QRect(59, 35, 22, 20))
        self.st_con_misc.setMaxLength(2)
        self.st_con_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_con_misc.setObjectName("st_con_misc")
        self.st_con_all = QtWidgets.QLabel(self.stats)
        self.st_con_all.setGeometry(QtCore.QRect(83, 35, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_con_all.setFont(font)
        self.st_con_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_con_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_con_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_con_all.setObjectName("st_con_all")
        self.st_con_origin = QtWidgets.QLineEdit(self.stats)
        self.st_con_origin.setGeometry(QtCore.QRect(35, 35, 22, 20))
        self.st_con_origin.setMaxLength(2)
        self.st_con_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_con_origin.setObjectName("st_con_origin")
        self.st_con_mod = QtWidgets.QLabel(self.stats)
        self.st_con_mod.setGeometry(QtCore.QRect(107, 35, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_con_mod.setFont(font)
        self.st_con_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_con_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_con_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_con_mod.setObjectName("st_con_mod")
        self.st_int_misc = QtWidgets.QLineEdit(self.stats)
        self.st_int_misc.setGeometry(QtCore.QRect(59, 77, 22, 20))
        self.st_int_misc.setMaxLength(2)
        self.st_int_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_int_misc.setObjectName("st_int_misc")
        self.st_int_all = QtWidgets.QLabel(self.stats)
        self.st_int_all.setGeometry(QtCore.QRect(83, 77, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_int_all.setFont(font)
        self.st_int_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_int_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_int_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_int_all.setObjectName("st_int_all")
        self.st_int_origin = QtWidgets.QLineEdit(self.stats)
        self.st_int_origin.setGeometry(QtCore.QRect(35, 77, 22, 20))
        self.st_int_origin.setMaxLength(2)
        self.st_int_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_int_origin.setObjectName("st_int_origin")
        self.st_int_mod = QtWidgets.QLabel(self.stats)
        self.st_int_mod.setGeometry(QtCore.QRect(107, 77, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_int_mod.setFont(font)
        self.st_int_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_int_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_int_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_int_mod.setObjectName("st_int_mod")
        self.st_wis_misc = QtWidgets.QLineEdit(self.stats)
        self.st_wis_misc.setGeometry(QtCore.QRect(59, 98, 22, 20))
        self.st_wis_misc.setMaxLength(2)
        self.st_wis_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_wis_misc.setObjectName("st_wis_misc")
        self.st_wis_all = QtWidgets.QLabel(self.stats)
        self.st_wis_all.setGeometry(QtCore.QRect(83, 98, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_wis_all.setFont(font)
        self.st_wis_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_wis_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_wis_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_wis_all.setObjectName("st_wis_all")
        self.st_wis_origin = QtWidgets.QLineEdit(self.stats)
        self.st_wis_origin.setGeometry(QtCore.QRect(35, 98, 22, 20))
        self.st_wis_origin.setMaxLength(2)
        self.st_wis_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_wis_origin.setObjectName("st_wis_origin")
        self.st_wis_mod = QtWidgets.QLabel(self.stats)
        self.st_wis_mod.setGeometry(QtCore.QRect(107, 98, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_wis_mod.setFont(font)
        self.st_wis_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_wis_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_wis_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_wis_mod.setObjectName("st_wis_mod")
        self.st_cha_misc = QtWidgets.QLineEdit(self.stats)
        self.st_cha_misc.setGeometry(QtCore.QRect(59, 119, 22, 20))
        self.st_cha_misc.setMaxLength(2)
        self.st_cha_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_cha_misc.setObjectName("st_cha_misc")
        self.st_cha_all = QtWidgets.QLabel(self.stats)
        self.st_cha_all.setGeometry(QtCore.QRect(83, 119, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_cha_all.setFont(font)
        self.st_cha_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_cha_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_cha_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_cha_all.setObjectName("st_cha_all")
        self.st_cha_origin = QtWidgets.QLineEdit(self.stats)
        self.st_cha_origin.setGeometry(QtCore.QRect(35, 119, 22, 20))
        self.st_cha_origin.setMaxLength(2)
        self.st_cha_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_cha_origin.setObjectName("st_cha_origin")
        self.st_cha_mod = QtWidgets.QLabel(self.stats)
        self.st_cha_mod.setGeometry(QtCore.QRect(107, 119, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_cha_mod.setFont(font)
        self.st_cha_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_cha_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_cha_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_cha_mod.setObjectName("st_cha_mod")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 20, 60, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        self.LvL = QtWidgets.QLineEdit(self.centralwidget)
        self.LvL.setGeometry(QtCore.QRect(553, 20, 21, 21))
        self.LvL.setObjectName("LvL")
        self.skills = QtWidgets.QGroupBox(self.centralwidget)
        self.skills.setGeometry(QtCore.QRect(0, 220, 261, 481))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 194, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 194, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 194, 194))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.skills.setPalette(palette)
        self.skills.setAlignment(QtCore.Qt.AlignCenter)
        self.skills.setFlat(True)
        self.skills.setObjectName("skills")
        self.pushButton_31 = QtWidgets.QPushButton(self.skills)
        self.pushButton_31.setGeometry(QtCore.QRect(30, 414, 91, 23))
        self.pushButton_31.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.sk_dipl_sum = QtWidgets.QLabel(self.skills)
        self.sk_dipl_sum.setGeometry(QtCore.QRect(7, 114, 21, 23))
        self.sk_dipl_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_dipl_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_dipl_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_dipl_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_dipl_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_dipl_sum.setText("")
        self.sk_dipl_sum.setObjectName("sk_dipl_sum")
        self.pushButton_6 = QtWidgets.QPushButton(self.skills)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 189, 91, 23))
        self.pushButton_6.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_27 = QtWidgets.QPushButton(self.skills)
        self.pushButton_27.setGeometry(QtCore.QRect(30, 389, 91, 23))
        self.pushButton_27.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.sk_perc_sum = QtWidgets.QLabel(self.skills)
        self.sk_perc_sum.setGeometry(QtCore.QRect(7, 314, 21, 23))
        self.sk_perc_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_perc_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_perc_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_perc_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_perc_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_perc_sum.setText("")
        self.sk_perc_sum.setObjectName("sk_perc_sum")
        self.pushButton_29 = QtWidgets.QPushButton(self.skills)
        self.pushButton_29.setGeometry(QtCore.QRect(30, 314, 91, 23))
        self.pushButton_29.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.sk_heal_sum = QtWidgets.QLabel(self.skills)
        self.sk_heal_sum.setGeometry(QtCore.QRect(7, 189, 21, 23))
        self.sk_heal_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_heal_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_heal_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_heal_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_heal_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_heal_sum.setText("")
        self.sk_heal_sum.setObjectName("sk_heal_sum")
        self.pushButton_5 = QtWidgets.QPushButton(self.skills)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 64, 91, 23))
        self.pushButton_5.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.sk_bluff_sum = QtWidgets.QLabel(self.skills)
        self.sk_bluff_sum.setGeometry(QtCore.QRect(7, 89, 21, 23))
        self.sk_bluff_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_bluff_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_bluff_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_bluff_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_bluff_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_bluff_sum.setText("")
        self.sk_bluff_sum.setObjectName("sk_bluff_sum")
        self.sk_int_sum = QtWidgets.QLabel(self.skills)
        self.sk_int_sum.setGeometry(QtCore.QRect(7, 264, 21, 23))
        self.sk_int_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_int_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_int_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_int_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_int_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_int_sum.setText("")
        self.sk_int_sum.setObjectName("sk_int_sum")
        self.pushButton_26 = QtWidgets.QPushButton(self.skills)
        self.pushButton_26.setGeometry(QtCore.QRect(30, 214, 91, 23))
        self.pushButton_26.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_24 = QtWidgets.QPushButton(self.skills)
        self.pushButton_24.setGeometry(QtCore.QRect(30, 239, 92, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_4 = QtWidgets.QPushButton(self.skills)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 89, 91, 23))
        self.pushButton_4.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.sk_stealth_sum = QtWidgets.QLabel(self.skills)
        self.sk_stealth_sum.setGeometry(QtCore.QRect(7, 364, 21, 23))
        self.sk_stealth_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_stealth_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_stealth_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_stealth_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_stealth_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_stealth_sum.setText("")
        self.sk_stealth_sum.setObjectName("sk_stealth_sum")
        self.sk_street_sum = QtWidgets.QLabel(self.skills)
        self.sk_street_sum.setGeometry(QtCore.QRect(7, 389, 21, 23))
        self.sk_street_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_street_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_street_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_street_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_street_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_street_sum.setText("")
        self.sk_street_sum.setObjectName("sk_street_sum")
        self.pushButton_23 = QtWidgets.QPushButton(self.skills)
        self.pushButton_23.setGeometry(QtCore.QRect(30, 364, 91, 23))
        self.pushButton_23.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.sk_athl_sum = QtWidgets.QLabel(self.skills)
        self.sk_athl_sum.setGeometry(QtCore.QRect(7, 64, 21, 23))
        self.sk_athl_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_athl_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_athl_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_athl_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_athl_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_athl_sum.setText("")
        self.sk_athl_sum.setObjectName("sk_athl_sum")
        self.sk_dung_sum = QtWidgets.QLabel(self.skills)
        self.sk_dung_sum.setGeometry(QtCore.QRect(7, 139, 21, 23))
        self.sk_dung_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_dung_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_dung_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_dung_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_dung_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_dung_sum.setText("")
        self.sk_dung_sum.setObjectName("sk_dung_sum")
        self.sk_arc_sum = QtWidgets.QLabel(self.skills)
        self.sk_arc_sum.setGeometry(QtCore.QRect(7, 39, 21, 23))
        self.sk_arc_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_arc_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_arc_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_arc_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_arc_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_arc_sum.setText("")
        self.sk_arc_sum.setObjectName("sk_arc_sum")
        self.sk_acr_sum = QtWidgets.QLabel(self.skills)
        self.sk_acr_sum.setGeometry(QtCore.QRect(7, 14, 21, 23))
        self.sk_acr_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_acr_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_acr_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_acr_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_acr_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_acr_sum.setText("")
        self.sk_acr_sum.setObjectName("sk_acr_sum")
        self.sk_nat_sum = QtWidgets.QLabel(self.skills)
        self.sk_nat_sum.setGeometry(QtCore.QRect(7, 289, 21, 23))
        self.sk_nat_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_nat_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_nat_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_nat_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_nat_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_nat_sum.setText("")
        self.sk_nat_sum.setObjectName("sk_nat_sum")
        self.pushButton_30 = QtWidgets.QPushButton(self.skills)
        self.pushButton_30.setGeometry(QtCore.QRect(30, 339, 91, 23))
        self.pushButton_30.setMinimumSize(QtCore.QSize(91, 0))
        self.pushButton_30.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_3 = QtWidgets.QPushButton(self.skills)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 39, 91, 23))
        self.pushButton_3.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.skills)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 139, 91, 23))
        self.pushButton_8.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.sk_end_sum = QtWidgets.QLabel(self.skills)
        self.sk_end_sum.setGeometry(QtCore.QRect(7, 164, 21, 23))
        self.sk_end_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_end_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_end_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_end_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_end_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_end_sum.setText("")
        self.sk_end_sum.setObjectName("sk_end_sum")
        self.pushButton = QtWidgets.QPushButton(self.skills)
        self.pushButton.setGeometry(QtCore.QRect(30, 14, 91, 23))
        self.pushButton.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(self.skills)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 164, 91, 23))
        self.pushButton_9.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.sk_thief_sum = QtWidgets.QLabel(self.skills)
        self.sk_thief_sum.setGeometry(QtCore.QRect(7, 414, 21, 23))
        self.sk_thief_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_thief_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_thief_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_thief_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_thief_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_thief_sum.setText("")
        self.sk_thief_sum.setObjectName("sk_thief_sum")
        self.sk_ins_sum = QtWidgets.QLabel(self.skills)
        self.sk_ins_sum.setGeometry(QtCore.QRect(7, 239, 21, 23))
        self.sk_ins_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_ins_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_ins_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_ins_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_ins_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_ins_sum.setText("")
        self.sk_ins_sum.setObjectName("sk_ins_sum")
        self.pushButton_25 = QtWidgets.QPushButton(self.skills)
        self.pushButton_25.setGeometry(QtCore.QRect(30, 264, 91, 23))
        self.pushButton_25.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_10 = QtWidgets.QPushButton(self.skills)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 114, 91, 23))
        self.pushButton_10.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_28 = QtWidgets.QPushButton(self.skills)
        self.pushButton_28.setGeometry(QtCore.QRect(30, 289, 91, 23))
        self.pushButton_28.setMinimumSize(QtCore.QSize(91, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.sk_hist_sum = QtWidgets.QLabel(self.skills)
        self.sk_hist_sum.setGeometry(QtCore.QRect(7, 214, 21, 23))
        self.sk_hist_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_hist_sum.setMaximumSize(QtCore.QSize(21, 23))
        self.sk_hist_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_hist_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_hist_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_hist_sum.setText("")
        self.sk_hist_sum.setObjectName("sk_hist_sum")
        self.sk_rel_sum = QtWidgets.QLabel(self.skills)
        self.sk_rel_sum.setGeometry(QtCore.QRect(7, 339, 21, 23))
        self.sk_rel_sum.setMinimumSize(QtCore.QSize(21, 21))
        self.sk_rel_sum.setMaximumSize(QtCore.QSize(21, 16777215))
        self.sk_rel_sum.setBaseSize(QtCore.QSize(23, 23))
        self.sk_rel_sum.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sk_rel_sum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sk_rel_sum.setText("")
        self.sk_rel_sum.setObjectName("sk_rel_sum")
        self.con_mod_here = QtWidgets.QLabel(self.skills)
        self.con_mod_here.setGeometry(QtCore.QRect(124, 164, 21, 23))
        self.con_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.con_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.con_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.con_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.con_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.con_mod_here.setText("")
        self.con_mod_here.setObjectName("con_mod_here")
        self.dex_mod_here_2 = QtWidgets.QLabel(self.skills)
        self.dex_mod_here_2.setGeometry(QtCore.QRect(124, 364, 21, 23))
        self.dex_mod_here_2.setMinimumSize(QtCore.QSize(21, 21))
        self.dex_mod_here_2.setMaximumSize(QtCore.QSize(21, 23))
        self.dex_mod_here_2.setBaseSize(QtCore.QSize(23, 23))
        self.dex_mod_here_2.setFrameShape(QtWidgets.QFrame.Box)
        self.dex_mod_here_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dex_mod_here_2.setText("")
        self.dex_mod_here_2.setObjectName("dex_mod_here_2")
        self.wis_mod_here_5 = QtWidgets.QLabel(self.skills)
        self.wis_mod_here_5.setGeometry(QtCore.QRect(124, 314, 21, 23))
        self.wis_mod_here_5.setMinimumSize(QtCore.QSize(21, 21))
        self.wis_mod_here_5.setMaximumSize(QtCore.QSize(21, 23))
        self.wis_mod_here_5.setBaseSize(QtCore.QSize(23, 23))
        self.wis_mod_here_5.setFrameShape(QtWidgets.QFrame.Box)
        self.wis_mod_here_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_mod_here_5.setText("")
        self.wis_mod_here_5.setObjectName("wis_mod_here_5")
        self.int_mod_here_3 = QtWidgets.QLabel(self.skills)
        self.int_mod_here_3.setGeometry(QtCore.QRect(124, 339, 21, 23))
        self.int_mod_here_3.setMinimumSize(QtCore.QSize(21, 21))
        self.int_mod_here_3.setMaximumSize(QtCore.QSize(21, 16777215))
        self.int_mod_here_3.setBaseSize(QtCore.QSize(23, 23))
        self.int_mod_here_3.setFrameShape(QtWidgets.QFrame.Box)
        self.int_mod_here_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.int_mod_here_3.setText("")
        self.int_mod_here_3.setObjectName("int_mod_here_3")
        self.st_mod_here = QtWidgets.QLabel(self.skills)
        self.st_mod_here.setGeometry(QtCore.QRect(124, 64, 21, 23))
        self.st_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.st_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.st_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.st_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.st_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_mod_here.setText("")
        self.st_mod_here.setObjectName("st_mod_here")
        self.wis_mod_here = QtWidgets.QLabel(self.skills)
        self.wis_mod_here.setGeometry(QtCore.QRect(124, 139, 21, 23))
        self.wis_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.wis_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.wis_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.wis_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.wis_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_mod_here.setText("")
        self.wis_mod_here.setObjectName("wis_mod_here")
        self.cha_mod_here = QtWidgets.QLabel(self.skills)
        self.cha_mod_here.setGeometry(QtCore.QRect(124, 89, 21, 23))
        self.cha_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.cha_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.cha_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.cha_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.cha_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cha_mod_here.setText("")
        self.cha_mod_here.setObjectName("cha_mod_here")
        self.int_mod_here = QtWidgets.QLabel(self.skills)
        self.int_mod_here.setGeometry(QtCore.QRect(124, 39, 21, 23))
        self.int_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.int_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.int_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.int_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.int_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.int_mod_here.setText("")
        self.int_mod_here.setObjectName("int_mod_here")
        self.wis_mod_here_4 = QtWidgets.QLabel(self.skills)
        self.wis_mod_here_4.setGeometry(QtCore.QRect(124, 289, 21, 23))
        self.wis_mod_here_4.setMinimumSize(QtCore.QSize(21, 21))
        self.wis_mod_here_4.setMaximumSize(QtCore.QSize(21, 23))
        self.wis_mod_here_4.setBaseSize(QtCore.QSize(23, 23))
        self.wis_mod_here_4.setFrameShape(QtWidgets.QFrame.Box)
        self.wis_mod_here_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_mod_here_4.setText("")
        self.wis_mod_here_4.setObjectName("wis_mod_here_4")
        self.wis_mod_here_2 = QtWidgets.QLabel(self.skills)
        self.wis_mod_here_2.setGeometry(QtCore.QRect(124, 189, 21, 23))
        self.wis_mod_here_2.setMinimumSize(QtCore.QSize(21, 21))
        self.wis_mod_here_2.setMaximumSize(QtCore.QSize(21, 23))
        self.wis_mod_here_2.setBaseSize(QtCore.QSize(23, 23))
        self.wis_mod_here_2.setFrameShape(QtWidgets.QFrame.Box)
        self.wis_mod_here_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_mod_here_2.setText("")
        self.wis_mod_here_2.setObjectName("wis_mod_here_2")
        self.cha_mod_here_2 = QtWidgets.QLabel(self.skills)
        self.cha_mod_here_2.setGeometry(QtCore.QRect(124, 114, 21, 23))
        self.cha_mod_here_2.setMinimumSize(QtCore.QSize(21, 21))
        self.cha_mod_here_2.setMaximumSize(QtCore.QSize(21, 23))
        self.cha_mod_here_2.setBaseSize(QtCore.QSize(23, 23))
        self.cha_mod_here_2.setFrameShape(QtWidgets.QFrame.Box)
        self.cha_mod_here_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cha_mod_here_2.setText("")
        self.cha_mod_here_2.setObjectName("cha_mod_here_2")
        self.cha_mod_here_3 = QtWidgets.QLabel(self.skills)
        self.cha_mod_here_3.setGeometry(QtCore.QRect(124, 264, 21, 23))
        self.cha_mod_here_3.setMinimumSize(QtCore.QSize(21, 21))
        self.cha_mod_here_3.setMaximumSize(QtCore.QSize(21, 23))
        self.cha_mod_here_3.setBaseSize(QtCore.QSize(23, 23))
        self.cha_mod_here_3.setFrameShape(QtWidgets.QFrame.Box)
        self.cha_mod_here_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cha_mod_here_3.setText("")
        self.cha_mod_here_3.setObjectName("cha_mod_here_3")
        self.cha_mod_here_4 = QtWidgets.QLabel(self.skills)
        self.cha_mod_here_4.setGeometry(QtCore.QRect(124, 389, 21, 23))
        self.cha_mod_here_4.setMinimumSize(QtCore.QSize(21, 21))
        self.cha_mod_here_4.setMaximumSize(QtCore.QSize(21, 23))
        self.cha_mod_here_4.setBaseSize(QtCore.QSize(23, 23))
        self.cha_mod_here_4.setFrameShape(QtWidgets.QFrame.Box)
        self.cha_mod_here_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cha_mod_here_4.setText("")
        self.cha_mod_here_4.setObjectName("cha_mod_here_4")
        self.dex_mod_here_3 = QtWidgets.QLabel(self.skills)
        self.dex_mod_here_3.setGeometry(QtCore.QRect(124, 414, 21, 23))
        self.dex_mod_here_3.setMinimumSize(QtCore.QSize(21, 21))
        self.dex_mod_here_3.setMaximumSize(QtCore.QSize(21, 23))
        self.dex_mod_here_3.setBaseSize(QtCore.QSize(23, 23))
        self.dex_mod_here_3.setFrameShape(QtWidgets.QFrame.Box)
        self.dex_mod_here_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dex_mod_here_3.setText("")
        self.dex_mod_here_3.setObjectName("dex_mod_here_3")
        self.wis_mod_here_3 = QtWidgets.QLabel(self.skills)
        self.wis_mod_here_3.setGeometry(QtCore.QRect(124, 239, 21, 23))
        self.wis_mod_here_3.setMinimumSize(QtCore.QSize(21, 21))
        self.wis_mod_here_3.setMaximumSize(QtCore.QSize(21, 23))
        self.wis_mod_here_3.setBaseSize(QtCore.QSize(23, 23))
        self.wis_mod_here_3.setFrameShape(QtWidgets.QFrame.Box)
        self.wis_mod_here_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_mod_here_3.setText("")
        self.wis_mod_here_3.setObjectName("wis_mod_here_3")
        self.dex_mod_here = QtWidgets.QLabel(self.skills)
        self.dex_mod_here.setGeometry(QtCore.QRect(124, 14, 21, 23))
        self.dex_mod_here.setMinimumSize(QtCore.QSize(21, 21))
        self.dex_mod_here.setMaximumSize(QtCore.QSize(21, 23))
        self.dex_mod_here.setBaseSize(QtCore.QSize(23, 23))
        self.dex_mod_here.setFrameShape(QtWidgets.QFrame.Box)
        self.dex_mod_here.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dex_mod_here.setObjectName("dex_mod_here")
        self.int_mod_here_2 = QtWidgets.QLabel(self.skills)
        self.int_mod_here_2.setGeometry(QtCore.QRect(124, 214, 21, 23))
        self.int_mod_here_2.setMinimumSize(QtCore.QSize(21, 21))
        self.int_mod_here_2.setMaximumSize(QtCore.QSize(21, 23))
        self.int_mod_here_2.setBaseSize(QtCore.QSize(23, 23))
        self.int_mod_here_2.setFrameShape(QtWidgets.QFrame.Box)
        self.int_mod_here_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.int_mod_here_2.setText("")
        self.int_mod_here_2.setObjectName("int_mod_here_2")
        self.istrained = QtWidgets.QCheckBox(self.skills)
        self.istrained.setGeometry(QtCore.QRect(150, 14, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained.sizePolicy().hasHeightForWidth())
        self.istrained.setSizePolicy(sizePolicy)
        self.istrained.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained.setFont(font)
        self.istrained.setIconSize(QtCore.QSize(23, 23))
        self.istrained.setChecked(False)
        self.istrained.setTristate(False)
        self.istrained.setObjectName("istrained")
        self.istrained_2 = QtWidgets.QCheckBox(self.skills)
        self.istrained_2.setGeometry(QtCore.QRect(150, 39, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_2.sizePolicy().hasHeightForWidth())
        self.istrained_2.setSizePolicy(sizePolicy)
        self.istrained_2.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_2.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_2.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_2.setFont(font)
        self.istrained_2.setIconSize(QtCore.QSize(23, 23))
        self.istrained_2.setChecked(False)
        self.istrained_2.setTristate(False)
        self.istrained_2.setObjectName("istrained_2")
        self.istrained_3 = QtWidgets.QCheckBox(self.skills)
        self.istrained_3.setGeometry(QtCore.QRect(150, 64, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_3.sizePolicy().hasHeightForWidth())
        self.istrained_3.setSizePolicy(sizePolicy)
        self.istrained_3.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_3.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_3.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_3.setFont(font)
        self.istrained_3.setIconSize(QtCore.QSize(23, 23))
        self.istrained_3.setChecked(False)
        self.istrained_3.setTristate(False)
        self.istrained_3.setObjectName("istrained_3")
        self.istrained_4 = QtWidgets.QCheckBox(self.skills)
        self.istrained_4.setGeometry(QtCore.QRect(150, 89, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_4.sizePolicy().hasHeightForWidth())
        self.istrained_4.setSizePolicy(sizePolicy)
        self.istrained_4.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_4.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_4.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_4.setFont(font)
        self.istrained_4.setIconSize(QtCore.QSize(23, 23))
        self.istrained_4.setChecked(False)
        self.istrained_4.setTristate(False)
        self.istrained_4.setObjectName("istrained_4")
        self.istrained_5 = QtWidgets.QCheckBox(self.skills)
        self.istrained_5.setGeometry(QtCore.QRect(150, 114, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_5.sizePolicy().hasHeightForWidth())
        self.istrained_5.setSizePolicy(sizePolicy)
        self.istrained_5.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_5.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_5.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_5.setFont(font)
        self.istrained_5.setIconSize(QtCore.QSize(23, 23))
        self.istrained_5.setChecked(False)
        self.istrained_5.setTristate(False)
        self.istrained_5.setObjectName("istrained_5")
        self.istrained_7 = QtWidgets.QCheckBox(self.skills)
        self.istrained_7.setGeometry(QtCore.QRect(150, 139, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_7.sizePolicy().hasHeightForWidth())
        self.istrained_7.setSizePolicy(sizePolicy)
        self.istrained_7.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_7.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_7.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_7.setFont(font)
        self.istrained_7.setIconSize(QtCore.QSize(23, 23))
        self.istrained_7.setChecked(False)
        self.istrained_7.setTristate(False)
        self.istrained_7.setObjectName("istrained_7")
        self.istrained_8 = QtWidgets.QCheckBox(self.skills)
        self.istrained_8.setGeometry(QtCore.QRect(150, 164, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_8.sizePolicy().hasHeightForWidth())
        self.istrained_8.setSizePolicy(sizePolicy)
        self.istrained_8.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_8.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_8.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_8.setFont(font)
        self.istrained_8.setIconSize(QtCore.QSize(23, 23))
        self.istrained_8.setChecked(False)
        self.istrained_8.setTristate(False)
        self.istrained_8.setObjectName("istrained_8")
        self.istrained_9 = QtWidgets.QCheckBox(self.skills)
        self.istrained_9.setGeometry(QtCore.QRect(150, 189, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_9.sizePolicy().hasHeightForWidth())
        self.istrained_9.setSizePolicy(sizePolicy)
        self.istrained_9.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_9.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_9.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_9.setFont(font)
        self.istrained_9.setIconSize(QtCore.QSize(23, 23))
        self.istrained_9.setChecked(False)
        self.istrained_9.setTristate(False)
        self.istrained_9.setObjectName("istrained_9")
        self.istrained_12 = QtWidgets.QCheckBox(self.skills)
        self.istrained_12.setGeometry(QtCore.QRect(150, 214, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_12.sizePolicy().hasHeightForWidth())
        self.istrained_12.setSizePolicy(sizePolicy)
        self.istrained_12.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_12.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_12.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_12.setFont(font)
        self.istrained_12.setIconSize(QtCore.QSize(23, 23))
        self.istrained_12.setChecked(False)
        self.istrained_12.setTristate(False)
        self.istrained_12.setObjectName("istrained_12")
        self.istrained_10 = QtWidgets.QCheckBox(self.skills)
        self.istrained_10.setGeometry(QtCore.QRect(150, 239, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_10.sizePolicy().hasHeightForWidth())
        self.istrained_10.setSizePolicy(sizePolicy)
        self.istrained_10.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_10.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_10.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_10.setFont(font)
        self.istrained_10.setIconSize(QtCore.QSize(23, 23))
        self.istrained_10.setChecked(False)
        self.istrained_10.setTristate(False)
        self.istrained_10.setObjectName("istrained_10")
        self.istrained_16 = QtWidgets.QCheckBox(self.skills)
        self.istrained_16.setGeometry(QtCore.QRect(150, 264, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_16.sizePolicy().hasHeightForWidth())
        self.istrained_16.setSizePolicy(sizePolicy)
        self.istrained_16.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_16.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_16.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_16.setFont(font)
        self.istrained_16.setIconSize(QtCore.QSize(23, 23))
        self.istrained_16.setChecked(False)
        self.istrained_16.setTristate(False)
        self.istrained_16.setObjectName("istrained_16")
        self.istrained_6 = QtWidgets.QCheckBox(self.skills)
        self.istrained_6.setGeometry(QtCore.QRect(150, 289, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_6.sizePolicy().hasHeightForWidth())
        self.istrained_6.setSizePolicy(sizePolicy)
        self.istrained_6.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_6.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_6.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_6.setFont(font)
        self.istrained_6.setIconSize(QtCore.QSize(23, 23))
        self.istrained_6.setChecked(False)
        self.istrained_6.setTristate(False)
        self.istrained_6.setObjectName("istrained_6")
        self.istrained_15 = QtWidgets.QCheckBox(self.skills)
        self.istrained_15.setGeometry(QtCore.QRect(150, 314, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_15.sizePolicy().hasHeightForWidth())
        self.istrained_15.setSizePolicy(sizePolicy)
        self.istrained_15.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_15.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_15.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_15.setFont(font)
        self.istrained_15.setIconSize(QtCore.QSize(23, 23))
        self.istrained_15.setChecked(False)
        self.istrained_15.setTristate(False)
        self.istrained_15.setObjectName("istrained_15")
        self.istrained_14 = QtWidgets.QCheckBox(self.skills)
        self.istrained_14.setGeometry(QtCore.QRect(150, 339, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_14.sizePolicy().hasHeightForWidth())
        self.istrained_14.setSizePolicy(sizePolicy)
        self.istrained_14.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_14.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_14.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_14.setFont(font)
        self.istrained_14.setIconSize(QtCore.QSize(23, 23))
        self.istrained_14.setChecked(False)
        self.istrained_14.setTristate(False)
        self.istrained_14.setObjectName("istrained_14")
        self.istrained_17 = QtWidgets.QCheckBox(self.skills)
        self.istrained_17.setGeometry(QtCore.QRect(150, 364, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_17.sizePolicy().hasHeightForWidth())
        self.istrained_17.setSizePolicy(sizePolicy)
        self.istrained_17.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_17.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_17.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_17.setFont(font)
        self.istrained_17.setIconSize(QtCore.QSize(23, 23))
        self.istrained_17.setChecked(False)
        self.istrained_17.setTristate(False)
        self.istrained_17.setObjectName("istrained_17")
        self.istrained_13 = QtWidgets.QCheckBox(self.skills)
        self.istrained_13.setGeometry(QtCore.QRect(150, 389, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_13.sizePolicy().hasHeightForWidth())
        self.istrained_13.setSizePolicy(sizePolicy)
        self.istrained_13.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_13.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_13.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_13.setFont(font)
        self.istrained_13.setIconSize(QtCore.QSize(23, 23))
        self.istrained_13.setChecked(False)
        self.istrained_13.setTristate(False)
        self.istrained_13.setObjectName("istrained_13")
        self.istrained_11 = QtWidgets.QCheckBox(self.skills)
        self.istrained_11.setGeometry(QtCore.QRect(150, 414, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.istrained_11.sizePolicy().hasHeightForWidth())
        self.istrained_11.setSizePolicy(sizePolicy)
        self.istrained_11.setMaximumSize(QtCore.QSize(600, 600))
        self.istrained_11.setSizeIncrement(QtCore.QSize(36, 36))
        self.istrained_11.setBaseSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.istrained_11.setFont(font)
        self.istrained_11.setIconSize(QtCore.QSize(23, 23))
        self.istrained_11.setChecked(False)
        self.istrained_11.setTristate(False)
        self.istrained_11.setObjectName("istrained_11")
        self.noarmorpenalty = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty.setGeometry(QtCore.QRect(205, 39, 21, 23))
        self.noarmorpenalty.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty.setObjectName("noarmorpenalty")
        self.noarmorpenalty_2 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_2.setGeometry(QtCore.QRect(205, 89, 21, 23))
        self.noarmorpenalty_2.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_2.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_2.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_2.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_2.setObjectName("noarmorpenalty_2")
        self.noarmorpenalty_4 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_4.setGeometry(QtCore.QRect(205, 114, 21, 23))
        self.noarmorpenalty_4.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_4.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_4.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_4.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_4.setObjectName("noarmorpenalty_4")
        self.noarmorpenalty_10 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_10.setGeometry(QtCore.QRect(205, 139, 21, 23))
        self.noarmorpenalty_10.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_10.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_10.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_10.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_10.setObjectName("noarmorpenalty_10")
        self.noarmorpenalty_8 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_8.setGeometry(QtCore.QRect(205, 189, 21, 23))
        self.noarmorpenalty_8.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_8.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_8.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_8.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_8.setObjectName("noarmorpenalty_8")
        self.noarmorpenalty_9 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_9.setGeometry(QtCore.QRect(205, 214, 21, 23))
        self.noarmorpenalty_9.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_9.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_9.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_9.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_9.setObjectName("noarmorpenalty_9")
        self.noarmorpenalty_5 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_5.setGeometry(QtCore.QRect(205, 239, 21, 23))
        self.noarmorpenalty_5.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_5.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_5.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_5.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_5.setObjectName("noarmorpenalty_5")
        self.noarmorpenalty_6 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_6.setGeometry(QtCore.QRect(205, 264, 21, 23))
        self.noarmorpenalty_6.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_6.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_6.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_6.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_6.setObjectName("noarmorpenalty_6")
        self.noarmorpenalty_11 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_11.setGeometry(QtCore.QRect(205, 289, 21, 23))
        self.noarmorpenalty_11.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_11.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_11.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_11.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_11.setObjectName("noarmorpenalty_11")
        self.noarmorpenalty_7 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_7.setGeometry(QtCore.QRect(205, 339, 21, 23))
        self.noarmorpenalty_7.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_7.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_7.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_7.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_7.setObjectName("noarmorpenalty_7")
        self.noarmorpenalty_12 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_12.setGeometry(QtCore.QRect(205, 314, 21, 23))
        self.noarmorpenalty_12.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_12.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_12.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_12.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_12.setObjectName("noarmorpenalty_12")
        self.noarmorpenalty_3 = QtWidgets.QLabel(self.skills)
        self.noarmorpenalty_3.setGeometry(QtCore.QRect(205, 389, 21, 23))
        self.noarmorpenalty_3.setMinimumSize(QtCore.QSize(21, 21))
        self.noarmorpenalty_3.setMaximumSize(QtCore.QSize(21, 23))
        self.noarmorpenalty_3.setBaseSize(QtCore.QSize(23, 23))
        self.noarmorpenalty_3.setFrameShape(QtWidgets.QFrame.Box)
        self.noarmorpenalty_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.noarmorpenalty_3.setObjectName("noarmorpenalty_3")
        self.armorpenalty = QtWidgets.QLineEdit(self.skills)
        self.armorpenalty.setGeometry(QtCore.QRect(205, 14, 21, 23))
        self.armorpenalty.setObjectName("armorpenalty")
        self.armorpenalty_2 = QtWidgets.QLineEdit(self.skills)
        self.armorpenalty_2.setGeometry(QtCore.QRect(205, 64, 21, 23))
        self.armorpenalty_2.setObjectName("armorpenalty_2")
        self.armorpenalty_3 = QtWidgets.QLineEdit(self.skills)
        self.armorpenalty_3.setGeometry(QtCore.QRect(205, 164, 21, 23))
        self.armorpenalty_3.setObjectName("armorpenalty_3")
        self.sk_misc = QtWidgets.QLineEdit(self.skills)
        self.sk_misc.setGeometry(QtCore.QRect(230, 14, 21, 23))
        self.sk_misc.setObjectName("sk_misc")
        self.sk_misc_2 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_2.setGeometry(QtCore.QRect(230, 39, 21, 23))
        self.sk_misc_2.setObjectName("sk_misc_2")
        self.sk_misc_3 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_3.setGeometry(QtCore.QRect(230, 64, 21, 23))
        self.sk_misc_3.setObjectName("sk_misc_3")
        self.sk_misc_4 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_4.setGeometry(QtCore.QRect(230, 89, 21, 23))
        self.sk_misc_4.setObjectName("sk_misc_4")
        self.sk_misc_5 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_5.setGeometry(QtCore.QRect(230, 114, 21, 23))
        self.sk_misc_5.setObjectName("sk_misc_5")
        self.sk_misc_9 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_9.setGeometry(QtCore.QRect(230, 239, 21, 23))
        self.sk_misc_9.setObjectName("sk_misc_9")
        self.sk_misc_8 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_8.setGeometry(QtCore.QRect(230, 214, 21, 23))
        self.sk_misc_8.setObjectName("sk_misc_8")
        self.sk_misc_20 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_20.setGeometry(QtCore.QRect(230, 414, 21, 23))
        self.sk_misc_20.setObjectName("sk_misc_20")
        self.sk_misc_22 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_22.setGeometry(QtCore.QRect(230, 389, 21, 23))
        self.sk_misc_22.setObjectName("sk_misc_22")
        self.sk_misc_16 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_16.setGeometry(QtCore.QRect(230, 364, 21, 23))
        self.sk_misc_16.setObjectName("sk_misc_16")
        self.sk_misc_18 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_18.setGeometry(QtCore.QRect(230, 264, 21, 23))
        self.sk_misc_18.setObjectName("sk_misc_18")
        self.sk_misc_19 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_19.setGeometry(QtCore.QRect(230, 189, 21, 23))
        self.sk_misc_19.setObjectName("sk_misc_19")
        self.sk_misc_11 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_11.setGeometry(QtCore.QRect(230, 289, 21, 23))
        self.sk_misc_11.setObjectName("sk_misc_11")
        self.sk_misc_12 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_12.setGeometry(QtCore.QRect(230, 314, 21, 23))
        self.sk_misc_12.setObjectName("sk_misc_12")
        self.sk_misc_13 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_13.setGeometry(QtCore.QRect(230, 339, 21, 23))
        self.sk_misc_13.setObjectName("sk_misc_13")
        self.sk_misc_7 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_7.setGeometry(QtCore.QRect(230, 164, 21, 23))
        self.sk_misc_7.setObjectName("sk_misc_7")
        self.sk_misc_6 = QtWidgets.QLineEdit(self.skills)
        self.sk_misc_6.setGeometry(QtCore.QRect(230, 139, 21, 23))
        self.sk_misc_6.setObjectName("sk_misc_6")
        self.st_dex_mod = QtWidgets.QLabel(self.centralwidget)
        self.st_dex_mod.setGeometry(QtCore.QRect(115, 131, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_dex_mod.setFont(font)
        self.st_dex_mod.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.st_dex_mod.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_dex_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dex_mod.setObjectName("st_dex_mod")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 130, 32, 22))
        self.pushButton_7.setObjectName("pushButton_7")
        self.st_dex_misc = QtWidgets.QLineEdit(self.centralwidget)
        self.st_dex_misc.setGeometry(QtCore.QRect(67, 131, 22, 20))
        self.st_dex_misc.setMaxLength(2)
        self.st_dex_misc.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dex_misc.setObjectName("st_dex_misc")
        self.st_dex_origin = QtWidgets.QLineEdit(self.centralwidget)
        self.st_dex_origin.setGeometry(QtCore.QRect(43, 131, 22, 20))
        self.st_dex_origin.setMaxLength(2)
        self.st_dex_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dex_origin.setObjectName("st_dex_origin")
        self.st_dex_all = QtWidgets.QLabel(self.centralwidget)
        self.st_dex_all.setGeometry(QtCore.QRect(91, 131, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.st_dex_all.setFont(font)
        self.st_dex_all.setFrameShape(QtWidgets.QFrame.Box)
        self.st_dex_all.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.st_dex_all.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dex_all.setObjectName("st_dex_all")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 70, 291, 211))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(9, 9, 51, 51))
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/Shield-PNG-Image.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(51, 32, 75, 22))
        self.pushButton_2.setObjectName("pushButton_2")
        self.AC_sum = QtWidgets.QLabel(self.groupBox)
        self.AC_sum.setGeometry(QtCore.QRect(19, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(16)
        self.AC_sum.setFont(font)
        self.AC_sum.setTextFormat(QtCore.Qt.PlainText)
        self.AC_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.AC_sum.setObjectName("AC_sum")
        self.ten_and_halflevel = QtWidgets.QLabel(self.groupBox)
        self.ten_and_halflevel.setGeometry(QtCore.QRect(127, 33, 21, 21))
        self.ten_and_halflevel.setFrameShape(QtWidgets.QFrame.Box)
        self.ten_and_halflevel.setText("")
        self.ten_and_halflevel.setObjectName("ten_and_halflevel")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 56, 51, 51))
        self.label_13.setStyleSheet("")
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("icon/Shield-PNG-Image.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.ten_and_halflevel_2 = QtWidgets.QLabel(self.groupBox)
        self.ten_and_halflevel_2.setGeometry(QtCore.QRect(128, 80, 21, 21))
        self.ten_and_halflevel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ten_and_halflevel_2.setText("")
        self.ten_and_halflevel_2.setObjectName("ten_and_halflevel_2")
        self.FORT_sum = QtWidgets.QLabel(self.groupBox)
        self.FORT_sum.setGeometry(QtCore.QRect(20, 67, 31, 31))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(16)
        self.FORT_sum.setFont(font)
        self.FORT_sum.setTextFormat(QtCore.Qt.PlainText)
        self.FORT_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.FORT_sum.setObjectName("FORT_sum")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(52, 79, 75, 22))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(9, 106, 51, 51))
        self.label_20.setStyleSheet("")
        self.label_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("icon/Shield-PNG-Image.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.ten_and_halflevel_3 = QtWidgets.QLabel(self.groupBox)
        self.ten_and_halflevel_3.setGeometry(QtCore.QRect(127, 130, 21, 21))
        self.ten_and_halflevel_3.setFrameShape(QtWidgets.QFrame.Box)
        self.ten_and_halflevel_3.setText("")
        self.ten_and_halflevel_3.setObjectName("ten_and_halflevel_3")
        self.REF_sum = QtWidgets.QLabel(self.groupBox)
        self.REF_sum.setGeometry(QtCore.QRect(19, 117, 31, 31))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(16)
        self.REF_sum.setFont(font)
        self.REF_sum.setTextFormat(QtCore.Qt.PlainText)
        self.REF_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.REF_sum.setObjectName("REF_sum")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(51, 129, 75, 22))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(8, 157, 51, 51))
        self.label_32.setStyleSheet("")
        self.label_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("icon/Shield-PNG-Image.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.ten_and_halflevel_4 = QtWidgets.QLabel(self.groupBox)
        self.ten_and_halflevel_4.setGeometry(QtCore.QRect(126, 181, 21, 21))
        self.ten_and_halflevel_4.setFrameShape(QtWidgets.QFrame.Box)
        self.ten_and_halflevel_4.setText("")
        self.ten_and_halflevel_4.setObjectName("ten_and_halflevel_4")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setGeometry(QtCore.QRect(50, 180, 75, 22))
        self.pushButton_18.setObjectName("pushButton_18")
        self.WILL_sum = QtWidgets.QLabel(self.groupBox)
        self.WILL_sum.setGeometry(QtCore.QRect(18, 168, 31, 31))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(16)
        self.WILL_sum.setFont(font)
        self.WILL_sum.setTextFormat(QtCore.Qt.PlainText)
        self.WILL_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.WILL_sum.setObjectName("WILL_sum")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(-7, 6, 16, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.armor_dodge = QtWidgets.QLineEdit(self.groupBox)
        self.armor_dodge.setGeometry(QtCore.QRect(152, 33, 21, 21))
        self.armor_dodge.setObjectName("armor_dodge")
        self.class_bonus = QtWidgets.QLineEdit(self.groupBox)
        self.class_bonus.setGeometry(QtCore.QRect(174, 33, 21, 21))
        self.class_bonus.setObjectName("class_bonus")
        self.feat_bonus = QtWidgets.QLineEdit(self.groupBox)
        self.feat_bonus.setGeometry(QtCore.QRect(196, 33, 21, 21))
        self.feat_bonus.setObjectName("feat_bonus")
        self.misc_bonus = QtWidgets.QLineEdit(self.groupBox)
        self.misc_bonus.setGeometry(QtCore.QRect(240, 33, 21, 21))
        self.misc_bonus.setObjectName("misc_bonus")
        self.enh_bonus = QtWidgets.QLineEdit(self.groupBox)
        self.enh_bonus.setGeometry(QtCore.QRect(218, 33, 21, 21))
        self.enh_bonus.setObjectName("enh_bonus")
        self.feat_bonus_2 = QtWidgets.QLineEdit(self.groupBox)
        self.feat_bonus_2.setGeometry(QtCore.QRect(197, 80, 21, 21))
        self.feat_bonus_2.setObjectName("feat_bonus_2")
        self.enh_bonus_2 = QtWidgets.QLineEdit(self.groupBox)
        self.enh_bonus_2.setGeometry(QtCore.QRect(219, 80, 21, 21))
        self.enh_bonus_2.setObjectName("enh_bonus_2")
        self.ability_bonus = QtWidgets.QLineEdit(self.groupBox)
        self.ability_bonus.setGeometry(QtCore.QRect(153, 80, 21, 21))
        self.ability_bonus.setObjectName("ability_bonus")
        self.class_bonus_2 = QtWidgets.QLineEdit(self.groupBox)
        self.class_bonus_2.setGeometry(QtCore.QRect(175, 80, 21, 21))
        self.class_bonus_2.setObjectName("class_bonus_2")
        self.misc_bonus_2 = QtWidgets.QLineEdit(self.groupBox)
        self.misc_bonus_2.setGeometry(QtCore.QRect(241, 80, 21, 21))
        self.misc_bonus_2.setObjectName("misc_bonus_2")
        self.feat_bonus_3 = QtWidgets.QLineEdit(self.groupBox)
        self.feat_bonus_3.setGeometry(QtCore.QRect(196, 130, 21, 21))
        self.feat_bonus_3.setObjectName("feat_bonus_3")
        self.enh_bonus_3 = QtWidgets.QLineEdit(self.groupBox)
        self.enh_bonus_3.setGeometry(QtCore.QRect(218, 130, 21, 21))
        self.enh_bonus_3.setObjectName("enh_bonus_3")
        self.ability_bonus_2 = QtWidgets.QLineEdit(self.groupBox)
        self.ability_bonus_2.setGeometry(QtCore.QRect(152, 130, 21, 21))
        self.ability_bonus_2.setObjectName("ability_bonus_2")
        self.class_bonus_3 = QtWidgets.QLineEdit(self.groupBox)
        self.class_bonus_3.setGeometry(QtCore.QRect(174, 130, 21, 21))
        self.class_bonus_3.setObjectName("class_bonus_3")
        self.misc_bonus_3 = QtWidgets.QLineEdit(self.groupBox)
        self.misc_bonus_3.setGeometry(QtCore.QRect(240, 130, 21, 21))
        self.misc_bonus_3.setObjectName("misc_bonus_3")
        self.feat_bonus_4 = QtWidgets.QLineEdit(self.groupBox)
        self.feat_bonus_4.setGeometry(QtCore.QRect(196, 181, 21, 21))
        self.feat_bonus_4.setObjectName("feat_bonus_4")
        self.enh_bonus_4 = QtWidgets.QLineEdit(self.groupBox)
        self.enh_bonus_4.setGeometry(QtCore.QRect(218, 181, 21, 21))
        self.enh_bonus_4.setObjectName("enh_bonus_4")
        self.ability_bonus_3 = QtWidgets.QLineEdit(self.groupBox)
        self.ability_bonus_3.setGeometry(QtCore.QRect(152, 181, 21, 21))
        self.ability_bonus_3.setObjectName("ability_bonus_3")
        self.class_bonus_4 = QtWidgets.QLineEdit(self.groupBox)
        self.class_bonus_4.setGeometry(QtCore.QRect(174, 181, 21, 21))
        self.class_bonus_4.setObjectName("class_bonus_4")
        self.misc_bonus_4 = QtWidgets.QLineEdit(self.groupBox)
        self.misc_bonus_4.setGeometry(QtCore.QRect(240, 181, 21, 21))
        self.misc_bonus_4.setObjectName("misc_bonus_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(253, 227, 16, 151))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(262, 270, 291, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(543, 76, 16, 201))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(274, 284, 41, 30))
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.speed_sum = QtWidgets.QLabel(self.centralwidget)
        self.speed_sum.setGeometry(QtCore.QRect(283, 288, 23, 23))
        self.speed_sum.setText("")
        self.speed_sum.setObjectName("speed_sum")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(315, 289, 75, 22))
        self.pushButton_19.setObjectName("pushButton_19")
        self.PP_sum = QtWidgets.QLabel(self.centralwidget)
        self.PP_sum.setGeometry(QtCore.QRect(283, 327, 23, 23))
        self.PP_sum.setText("")
        self.PP_sum.setObjectName("PP_sum")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(274, 323, 41, 30))
        self.label_45.setFrameShape(QtWidgets.QFrame.Box)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(315, 328, 161, 22))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(315, 366, 161, 22))
        self.pushButton_21.setObjectName("pushButton_21")
        self.PI_sum = QtWidgets.QLabel(self.centralwidget)
        self.PI_sum.setGeometry(QtCore.QRect(283, 365, 23, 23))
        self.PI_sum.setText("")
        self.PI_sum.setObjectName("PI_sum")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(274, 361, 41, 30))
        self.label_47.setFrameShape(QtWidgets.QFrame.Box)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.ten = QtWidgets.QLabel(self.centralwidget)
        self.ten.setGeometry(QtCore.QRect(479, 328, 23, 23))
        self.ten.setFrameShape(QtWidgets.QFrame.Box)
        self.ten.setObjectName("ten")
        self.ten_2 = QtWidgets.QLabel(self.centralwidget)
        self.ten_2.setGeometry(QtCore.QRect(480, 365, 23, 23))
        self.ten_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ten_2.setObjectName("ten_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(253, 370, 16, 151))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(260, 400, 291, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(544, 278, 16, 131))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(280, 20, 60, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_52.setObjectName("label_52")
        self.character_class = QtWidgets.QLineEdit(self.centralwidget)
        self.character_class.setGeometry(QtCore.QRect(320, 20, 171, 20))
        self.character_class.setText("")
        self.character_class.setObjectName("character_class")
        self.armorpenalty_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.armorpenalty_4.setGeometry(QtCore.QRect(205, 584, 21, 23))
        self.armorpenalty_4.setObjectName("armorpenalty_4")
        self.armorpenalty_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.armorpenalty_5.setGeometry(QtCore.QRect(205, 634, 21, 23))
        self.armorpenalty_5.setObjectName("armorpenalty_5")
        self.sk_misc_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_misc_10.setGeometry(QtCore.QRect(230, 910, 21, 23))
        self.sk_misc_10.setObjectName("sk_misc_10")
        self.sk_misc_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_misc_21.setGeometry(QtCore.QRect(230, 860, 21, 23))
        self.sk_misc_21.setObjectName("sk_misc_21")
        self.sk_misc_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_misc_15.setGeometry(QtCore.QRect(230, 834, 21, 23))
        self.sk_misc_15.setObjectName("sk_misc_15")
        self.sk_misc_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_misc_14.setGeometry(QtCore.QRect(230, 935, 21, 23))
        self.sk_misc_14.setObjectName("sk_misc_14")
        self.sk_misc_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_misc_17.setGeometry(QtCore.QRect(230, 885, 21, 23))
        self.sk_misc_17.setObjectName("sk_misc_17")
        self.item_for_speed = QtWidgets.QLineEdit(self.centralwidget)
        self.item_for_speed.setGeometry(QtCore.QRect(437, 290, 21, 21))
        self.item_for_speed.setObjectName("item_for_speed")
        self.base_speed = QtWidgets.QLineEdit(self.centralwidget)
        self.base_speed.setGeometry(QtCore.QRect(393, 290, 21, 21))
        self.base_speed.setObjectName("base_speed")
        self.misc_speed = QtWidgets.QLineEdit(self.centralwidget)
        self.misc_speed.setGeometry(QtCore.QRect(459, 290, 21, 21))
        self.misc_speed.setObjectName("misc_speed")
        self.armor_penalty = QtWidgets.QLineEdit(self.centralwidget)
        self.armor_penalty.setGeometry(QtCore.QRect(415, 290, 21, 21))
        self.armor_penalty.setObjectName("armor_penalty")
        self.sk_perc_sum_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.sk_perc_sum_2.setGeometry(QtCore.QRect(507, 329, 21, 21))
        self.sk_perc_sum_2.setObjectName("sk_perc_sum_2")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(610, 390, 21, 21))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(508, 366, 21, 21))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.chatBox = QtWidgets.QGroupBox(self.centralwidget)
        self.chatBox.setGeometry(QtCore.QRect(280, 520, 401, 121))
        self.chatBox.setObjectName("chatBox")
        self.chat = QtWidgets.QTextEdit(self.chatBox)
        self.chat.setGeometry(QtCore.QRect(10, 20, 381, 91))
        self.chat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.chat.setReadOnly(True)
        self.chat.setPlaceholderText("")
        self.chat.setObjectName("chat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.char_name.setText(QtWidgets.QApplication.translate("MainWindow", "Имя Персонажа", None, -1))
        self.stats.setTitle(QtWidgets.QApplication.translate("MainWindow", "Статы", None, -1))
        self.st_str_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_str_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.st_str_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_str_all.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Итоговый стат: <span style=\" font-weight:400;\">8 + 0 = 8</span><br/>Формула: <span style=\" font-weight:400;\">&lt;БазовыйСтат&gt; + &lt;</span><span style=\" font-weight:400; color:#000000;\">ВременныйМод</span><span style=\" font-weight:400;\">&gt; = &lt;ИтоговыйСтат&gt;</span></p></body></html>", None, -1))
        self.st_str_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("MainWindow", "СИЛ", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("MainWindow", "ВЫН", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "ИНТ", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "МУД", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("MainWindow", "ХАР", None, -1))
        self.st_con_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_con_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_con_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_con_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.st_int_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_int_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_int_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_int_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.st_wis_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_wis_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_wis_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_wis_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.st_cha_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_cha_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_cha_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_cha_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Уровень:", None, -1))
        self.LvL.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.skills.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>Навык = мод. стата + 1/2 уровня + обученность(5(при наличии)) - штраф брони + прочее</p></body></html>", None, -1))
        self.skills.setTitle(QtWidgets.QApplication.translate("MainWindow", "Навыки", None, -1))
        self.pushButton_31.setText(QtWidgets.QApplication.translate("MainWindow", "Воровство", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Лечение", None, -1))
        self.pushButton_27.setText(QtWidgets.QApplication.translate("MainWindow", "Знание улиц", None, -1))
        self.pushButton_29.setText(QtWidgets.QApplication.translate("MainWindow", "Восприятие", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "Атлетика", None, -1))
        self.pushButton_26.setText(QtWidgets.QApplication.translate("MainWindow", "История", None, -1))
        self.pushButton_24.setText(QtWidgets.QApplication.translate("MainWindow", "Проницательность", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "Обман", None, -1))
        self.pushButton_23.setText(QtWidgets.QApplication.translate("MainWindow", "Скрытность", None, -1))
        self.pushButton_30.setText(QtWidgets.QApplication.translate("MainWindow", "Религия", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Магия", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "Подземелья", None, -1))
        self.pushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Акробатика", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("MainWindow", "Стойкость", None, -1))
        self.pushButton_25.setText(QtWidgets.QApplication.translate("MainWindow", "Запугивание", None, -1))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("MainWindow", "Дипломатия", None, -1))
        self.pushButton_28.setText(QtWidgets.QApplication.translate("MainWindow", "Природа", None, -1))
        self.dex_mod_here.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.istrained.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_2.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_3.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_4.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_5.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_7.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_8.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_9.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_12.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_10.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_16.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_6.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_15.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_14.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_17.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_13.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.istrained_11.setText(QtWidgets.QApplication.translate("MainWindow", "ТРЕН", None, -1))
        self.noarmorpenalty.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_2.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_4.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_10.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_8.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_9.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_5.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_6.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_11.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_7.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_12.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.noarmorpenalty_3.setText(QtWidgets.QApplication.translate("MainWindow", "n/a", None, -1))
        self.armorpenalty.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.sk_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_dex_mod.setText(QtWidgets.QApplication.translate("MainWindow", "-1", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "ЛОВ", None, -1))
        self.st_dex_misc.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.st_dex_origin.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.st_dex_all.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Защиты", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Класс Брони", None, -1))
        self.AC_sum.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.FORT_sum.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.pushButton_11.setText(QtWidgets.QApplication.translate("MainWindow", "Стойкость", None, -1))
        self.REF_sum.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "Реакция", None, -1))
        self.pushButton_18.setText(QtWidgets.QApplication.translate("MainWindow", "Воля", None, -1))
        self.WILL_sum.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.pushButton_19.setText(QtWidgets.QApplication.translate("MainWindow", "Скорость", None, -1))
        self.pushButton_20.setText(QtWidgets.QApplication.translate("MainWindow", "Пассивная внимательность", None, -1))
        self.pushButton_21.setText(QtWidgets.QApplication.translate("MainWindow", "Пассивная проницательность", None, -1))
        self.ten.setText(QtWidgets.QApplication.translate("MainWindow", "10", None, -1))
        self.ten_2.setText(QtWidgets.QApplication.translate("MainWindow", "10", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "Класс", None, -1))
        self.chatBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Чат", None, -1))
        self.chat.setHtml(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; font-style:italic;\">бросок </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Сила:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> 1d20</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; color:#aa0000;\">1</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">]</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> +СИЛ.Мод</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[3]</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> = 4</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; font-style:italic;\">бросок</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Сила:</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> 1d20</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600; color:#00aa00;\">20</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">]</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> +СИЛ.Мод</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">[3]</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> = 23</span></p></body></html>", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Файл", None, -1))
        self.action_2.setText(QtWidgets.QApplication.translate("MainWindow", "Открыть", None, -1))
        self.action_3.setText(QtWidgets.QApplication.translate("MainWindow", "Создать", None, -1))
        self.action_4.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить", None, -1))
        self.action_5.setText(QtWidgets.QApplication.translate("MainWindow", "Удалить", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

